# `dependabot.yml` file with
# customized schedule for version updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/integration-tests"
      - "/lambdas/*"
    schedule:
      interval: "daily"
      time: "02:00"
    groups:
      aws:
        patterns:
          - "@aws-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
