version: "3.8"

services:
  step_function_local:
    container_name: "stepfunction_local"
    image: amazon/aws-stepfunctions-local
    ports:
      - "8083:8083"
    env_file: .env
    volumes:
      - ./statemachine/tests/MockConfigFile.json:/home/stepfunctionslocal/MockConfigFile.json
