version = 0.1
[default.deploy.parameters]
stack_name = "otg-hmrc"
resolve_s3 = true
s3_prefix = "otg-hmrc"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = [
    "TotpSecretName=TotpSecretName",
    "ClientSecretName=HMRC_Client_Secret",
    "ClientId=HMRC_Client_Id",
    "OAuthUrl=https://test-api.service.hmrc.gov.uk/oauth/token",
    "BearerTokenName=HMRCBearerToken",
    "Environment=dev",
    "CommonStackName=common-cri-api",
    "CodeSigningEnabled=false"
]
