AWSTemplateFormatVersion: "2010-09-09"
Description: Digital Identity IPV HMRC OAuth Token Generator
Transform: [AWS::LanguageExtensions, AWS::Serverless-2016-10-31]

Parameters:
  SandboxOAuthUrl:
    Type: String
    Default: https://test-api.service.hmrc.gov.uk/oauth/token
  ProductionOAuthUrl:
    Type: String
    Default: https://api.service.hmrc.gov.uk/oauth/token
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, build, staging, integration, production]
  CodeSigningConfigArn:
    Type: String
    Default: ""
  PermissionsBoundary:
    Type: String
    Default: ""

Conditions:
  EnforceCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, ""]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]
  IsDevEnvironment: !Equals [!Ref Environment, dev]
  IsLocalDevEnvironment: !Equals [!Ref Environment, localdev]
  IsDevLikeEnvironment:
    !Or [!Condition IsLocalDevEnvironment, !Condition IsDevEnvironment]
  IsProdEnvironment: !Equals
    - !Ref Environment
    - production
  IsNotDevLikeEnvironment: !Not
    - !Condition IsDevLikeEnvironment
  IsNotProdEnvironment: !Not
    - !Condition IsProdEnvironment

Mappings:
  Dynatrace:
    SecretArn:
      dev: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      build: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      staging: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      integration: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
      production: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables

Globals:
  Function:
    Timeout: 30
    CodeUri: ..
    Runtime: nodejs18.x
    Architectures: [arm64]
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    VpcConfig:
      SecurityGroupIds:
        - !ImportValue otg-vpc-AWSServicesEndpointSecurityGroupId
      SubnetIds:
        - !ImportValue otg-vpc-ProtectedSubnetIdA
        - !ImportValue otg-vpc-ProtectedSubnetIdB
    Layers:
      - !Sub
        - "{{resolve:secretsmanager:${SecretArn}:SecretString:NODEJS_LAYER}}"
        - SecretArn: !FindInMap [Dynatrace, SecretArn, !Ref Environment]
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: true
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}"
          - SecretArn: !FindInMap [Dynatrace, SecretArn, !Ref Environment]
        DT_CONNECTION_BASE_URL: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}"
          - SecretArn: !FindInMap [Dynatrace, SecretArn, !Ref Environment]
        DT_CLUSTER_ID: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}"
          - SecretArn: !FindInMap [Dynatrace, SecretArn, !Ref Environment]
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}"
          - SecretArn: !FindInMap [Dynatrace, SecretArn, !Ref Environment]
        DT_TENANT: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}"
          - SecretArn: !FindInMap [Dynatrace, SecretArn, !Ref Environment]

Resources:
  StubTokenRefreshScheduler:
    Type: AWS::Scheduler::Schedule
    Condition: IsNotProdEnvironment
    Properties:
      Name: !Sub ${AWS::StackName}-stub
      Description: OTG refresh schedule for the stub token
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpression: rate(10 minutes)
      State: "ENABLED"
      Target:
        Arn: !Ref OAuthTokenStateMachine
        Input: '{ "tokenType": "stub" }'
        RetryPolicy:
          MaximumEventAgeInSeconds: 86400
          MaximumRetryAttempts: 185
        RoleArn: !GetAtt RefreshSchedulerRole.Arn

  SandboxTokenRefreshScheduler:
    Type: AWS::Scheduler::Schedule
    Condition: IsNotProdEnvironment
    Properties:
      Name: !Sub ${AWS::StackName}-sandbox
      Description: OTG refresh schedule for the sandbox token
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpression: rate(10 minutes)
      State: "ENABLED"
      Target:
        Arn: !Ref OAuthTokenStateMachine
        Input: '{ "tokenType": "sandbox" }'
        RetryPolicy:
          MaximumEventAgeInSeconds: 86400
          MaximumRetryAttempts: 185
        RoleArn: !GetAtt RefreshSchedulerRole.Arn

  ProductionTokenRefreshScheduler:
    Type: AWS::Scheduler::Schedule
    Condition: IsProdEnvironment
    Properties:
      Name: !Sub ${AWS::StackName}-production
      Description: OTG refresh schedule for the production token
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpression: rate(10 minutes)
      State: "ENABLED"
      Target:
        Arn: !Ref OAuthTokenStateMachine
        Input: '{ "tokenType": "production" }'
        RetryPolicy:
          MaximumEventAgeInSeconds: 86400
          MaximumRetryAttempts: 185
        RoleArn: !GetAtt RefreshSchedulerRole.Arn

  RefreshSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-RefreshSchedulerRole
      Description: Role to allow EventBridge to run a state machine
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: scheduler.amazonaws.com
      Policies:
        - PolicyName: AllowStateMachineInvoke
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Ref OAuthTokenStateMachine
                Action:
                  - states:StartExecution
                  - states:StartSyncExecution
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  StubOAuthUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/HMRC/OAuthURL/stub
      Type: String
      Value:
        !Join [
          "",
          [!ImportValue third-party-stubs-ImposterStubApiUrl, "/oauth/token"],
        ]
      Description: Imposter Mock of HMRC OAuth URL

  SandboxOAuthUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/HMRC/OAuthURL/sandbox
      Type: String
      Value: !Ref SandboxOAuthUrl
      Description: HMRC Sandbox OAuth URL

  ProductionOAuthUrlParameter:
    Condition: IsNotDevLikeEnvironment
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/HMRC/OAuthURL/production
      Type: String
      Value: !Ref ProductionOAuthUrl
      Description: HMRC Production OAuth URL

  PrivateOTGApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Private OAuth Token Generator API
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          DataTraceEnabled: true
          MetricsEnabled: true
          ThrottlingRateLimit: 200
          ThrottlingBurstLimit: 400
      AccessLogSetting:
        DestinationArn: !GetAtt PrivateOTGApiAccessLogGroup.Arn
        Format:
          Fn::ToJsonString:
            requestId: $context.requestId
            ip: $context.identity.sourceIp
            requestTime: $context.requestTime
            httpMethod: $context.httpMethod
            path: $context.path
            routeKey: $context.routeKey
            status: $context.status
            protocol: $context.protocol
            responseLatency: $context.responseLatency
            responseLength: $context.responseLength
      TracingEnabled: true
      Name: !Sub ${AWS::StackName}-private
      StageName: !Ref Environment
      DefinitionBody:
        openapi: 3.0.1
        paths:
          /never-created:
            options: {}
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: private-api.yaml
      OpenApiVersion: 3.0.1
      EndpointConfiguration:
        Type: !If [IsLocalDevEnvironment, REGIONAL, PRIVATE]
      Auth:
        ResourcePolicy: !If
          - IsLocalDevEnvironment
          - !Ref AWS::NoValue
          - CustomStatements:
              - Effect: Allow
                Resource: execute-api:/*
                Action: execute-api:Invoke
                Principal: "*"

  PrivateOTGApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/apigateway/${AWS::StackName}-${PrivateOTGApi}-private-AccessLogs
      RetentionInDays: !If [IsProdEnvironment, 30, 7]

  BearerTokenHandlerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Handler: lambdas/bearer-token-handler/src/bearer-token-handler.lambdaHandler
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/${AWS::StackName}/BearerTokenHandlerFunction
      CodeSigningConfigArn:
        !If [EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]

  BearerTokenHandlerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}/BearerTokenHandlerFunction
      RetentionInDays: !If [IsProdEnvironment, 30, 7]

  TotpGeneratorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Handler: lambdas/totp-generator/src/totp-generator-handler.lambdaHandler
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/${AWS::StackName}/TotpGeneratorFunction
      CodeSigningConfigArn:
        !If [EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]

  TotpGeneratorFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}/TotpGeneratorFunction
      RetentionInDays: !If [IsDevLikeEnvironment, 7, 30]

  OAuthTokenStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-OAuthTokenGenerator"
      DefinitionUri: ../step-functions/oauth-token-generator.asl.json
      DefinitionSubstitutions:
        TotpGeneratorFunctionArn: !GetAtt TotpGeneratorFunction.Arn
        BearerTokenFunctionArn: !GetAtt BearerTokenHandlerFunction.Arn
        StackName: !Ref AWS::StackName
        RefreshSchedulerRole: !Sub arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-RefreshSchedulerRole
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt OAuthTokenStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref TotpGeneratorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BearerTokenHandlerFunction
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:HMRC/TOTPSecret/*
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:HMRC/ClientSecret/*
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:HMRC/ClientId/*
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter*/HMRC/OAuthURL/*
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:PutSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:HMRC/BearerToken/*
        - Statement:
            - Effect: Allow
              Action:
                - scheduler:UpdateSchedule
              Resource: !Sub arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/*
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-RefreshSchedulerRole
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  OAuthTokenStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/vendedlogs/states/${AWS::StackName}-OAuth-state-machine-logs"
      RetentionInDays: !If [IsProdEnvironment, 30, 7]

  BearerTokenRetrievalStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Name: !Sub "${AWS::StackName}-BearerTokenRetrieval"
      DefinitionUri: ../step-functions/bearer-token-retrieval.asl.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt BearerTokenRetrievalStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:HMRC/BearerToken/*
        - Statement:
            Effect: Allow
            Action: logs:*
            Resource: "*"
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  BearerTokenRetrievalStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${AWS::StackName}-BearerTokenRetrievalStateMachine-state-machine-logs
      RetentionInDays: !If [IsDevLikeEnvironment, 7, 30]

  ExecuteStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role to allow API gateway to execute step function
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: apigateway.amazonaws.com
      Policies:
        - PolicyName: AllowStateMachineInvoke
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Ref BearerTokenRetrievalStateMachine
                Action:
                  - states:StartExecution
                  - states:StartSyncExecution
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  SuccessTokenGenerationMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref OAuthTokenStateMachineLogGroup
      FilterPattern: '{($.details.name = "Success")}'
      MetricTransformations:
        - MetricValue: 1
          MetricName: SuccessfulTokenGenerationMetric
          MetricNamespace: "otg-hmrc-service"

  FailTokenGenerationMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref OAuthTokenStateMachineLogGroup
      FilterPattern: '{($.details.name = "Fail")}'
      MetricTransformations:
        - MetricValue: 1
          MetricName: FailTokenGenerationMetric
          MetricNamespace: "otg-hmrc-service"

Outputs:
  PrivateApiGatewayId:
    Description: Private API Gateway ID for OAuth Token Generator
    Value: !Ref PrivateOTGApi
    Export:
      Name: !Sub ${AWS::StackName}-PrivateApiGatewayId
  OAuthTokenStateMachineArn:
    Description: OTG state machine ARN
    Value: !Ref OAuthTokenStateMachine
