AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Digital Identity IPV CRI Otg-Hmrc API"

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Timeout: 3

Parameters:
  TotpSecretName:
    Type: String

  ClientSecretName:
    Type: String

  BearerTokenSecretName:
    Type: String

  ClientId:
    Type: String

  OAuthUrl:
    Type: String

Resources:
  OAuthUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref OAuthUrl
      Description: HMRC OAuth Url

  BearerTokenExpiry:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: AWS::NoValue

  BearerTokenHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/bearer-token-handler
      Handler: bearer-token-handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: ["*"]
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/bearer-token-handler.ts

  OtgStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../step-functions/oauth-token-generator.asl.json
      DefinitionSubstitutions:
        TotpGeneratorFunctionArn: !GetAtt TotpGeneratorFunction.Arn
        BearerTokenFunctionArn: !GetAtt BearerTokenHandlerFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref TotpGeneratorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BearerTokenHandlerFunction
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*

  TotpGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/totp-generator
      Handler: totp-generator-handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: ["*"]
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/totp-generator-handler.ts

  OAuthTokenStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-OAuthTokenGenerator"
      DefinitionUri: ../step-functions/oauth-token-generator.asl.json
      DefinitionSubstitutions:
        TotpGeneratorFunctionArn: !GetAtt TotpGeneratorFunction.Arn
        BearerTokenFunctionArn: !GetAtt BearerTokenHandlerFunction.Arn
        BearerTokenSecretName: !Ref BearerTokenSecretName
        OAuthUrlParameter: !Ref OAuthUrlParameter
        BearerTokenExpiry: !Ref BearerTokenExpiry
        ClientSecretName: !Ref ClientSecretName
        TotpSecretName: !Ref TotpSecretName
        ClientId: !Ref ClientId
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref TotpGeneratorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BearerTokenHandlerFunction
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TotpSecretName}-??????
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ClientSecretName}-??????
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ClientId}-??????
        - SSMParameterReadPolicy:
            ParameterName: !Ref OAuthUrlParameter
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:PutSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BearerTokenSecretName}-??????
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${BearerTokenExpiry}

Outputs:
  BearerTokenHandlerFunctionURLEndpoint:
    Description: FURLFunction function name
    Value: !GetAtt BearerTokenHandlerFunctionUrl.FunctionUrl
  BearerTokenHandlerFunction:
    Description: "BearerTokenHandler Lambda Function ARN"
    Value: !GetAtt BearerTokenHandlerFunction.Arn
  BearerTokenHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for BearerTokenHandler function"
    Value: !GetAtt BearerTokenHandlerFunctionRole.Arn
  OtgStateMachineeArn:
    Description: Otg state machine ARN
    Value: !Ref OtgStateMachine
  OtgStateMachineRole:
    Description: "IAM Role created for Otg state machine based on the specified"
    Value: !GetAtt OtgStateMachineRole.Arn
  TotpGeneratorFunctionURLEndpoint:
    Description: FURLFunction function name
    Value: !GetAtt TotpGeneratorFunctionUrl.FunctionUrl
  TotpGeneratorFunction:
    Description: "TotpGenerator Lambda Function ARN"
    Value: !GetAtt TotpGeneratorFunction.Arn
  TotpGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for TotpGenerator function"
    Value: !GetAtt TotpGeneratorFunctionRole.Arn
