name: Lint and test lambdas

on:
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ["totp-generator"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: lambdas/${{ matrix.lambda }}

      - name: Lint
        run: npm run lint:eslint
        working-directory: lambdas/${{ matrix.lambda }}

      - name: Test
        run: npm test
        working-directory: lambdas/${{ matrix.lambda }}
