name: Deploy to Dev
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
      STACK_NAME: otg-hmrc
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.89.0

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_PRE_MERGE_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: sam validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/template.yaml

      - name: Install dependencies
        run: npm --prefix integration-tests install

      - name: sam build
        run: sam build -t infrastructure/template.yaml

      - name: sam deploy
        run: sam deploy --config-file infrastructure/samconfig.toml --stack-name ${{ env.STACK_NAME }}
